<a href="https://colab.research.google.com/github/J0SAL/Labs/blob/main/SC-IT312/lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [302]:
!python --version

Python 3.7.12


In [303]:
import numpy as np 
import matplotlib.pyplot as plt

### Defining the derivative to be used for back propogation 

In [304]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [305]:
def backward(x):
    return x * (1 - x)

In [306]:
# bipolar sigmoid for example 10
# def sigmoid (x):
#     return (2/(1 + np.exp(-x)))-1;

### Input datasets: Principles of softcomputing page 90, example 9

In [307]:
input_array = np.array([[0,1]])
target_array = np.array([[1]])
epochs = 1
l_rate = 0.25
input_Layer, hidden_Layer, output_Layer = 2,2,1
hw = [[0.6, -0.3],[-0.1, 0.4]] # ([v11 v12] [v21 v22])
hb = [[0.3, 0.5]] # ([v01 v02])
ow = [[0.4 ],[0.1]] # ([w1] [w2])
ob = [[-0.2]] # w0

Input datasets: Principles of softcomputing page 92, example 10

In [308]:
# input_array = np.array([[-1,1]])
# target_array = np.array([[1]])
# epochs = 1
# l_rate = 0.25
# input_Layer, hidden_Layer, output_Layer = 2,2,1
# hw = [[0.6, -0.3],[-0.1, 0.4]] # ([v11 v12] [v21 v22])
# hb = [[0.3, 0.5]] # ([v01 v02])
# ow = [[0.4 ],[0.1]] # ([w1] [w2])
# ob = [[-0.2]] # w0

### looking at the initial weights and biases

In [310]:
hidden_weights = np.array(hw)
hidden_bias = np.array(hb)
output_weights = np.array(ow)
output_bias = np.array(ob)


print("Start hidden weights: (v11 v12 v21 v22)\n ",hidden_weights)
print("Start hidden biases: (v01 v02)\n ",hidden_bias)
print("Start output weights: (w1 w2) \n ",output_weights)
print("Start output biases: (w0)\n ",output_bias)

Start hidden weights: (v11 v12 v21 v22)
  [[ 0.6 -0.3]
 [-0.1  0.4]]
Start hidden biases: (v01 v02)
  [[0.3 0.5]]
Start output weights: (w1 w2) 
  [[0.4]
 [0.1]]
Start output biases: (w0)
  [[-0.2]]


### Training algorithm to repeat for the number of epochs mentioned above

In [311]:
for i in range(epochs):
    #Forward Propagation of the network
    hidlayer_activation = np.dot(input_array,hidden_weights)
    hidlayer_activation = hidlayer_activation + hidden_bias
    hidlayer_output = sigmoid(hidlayer_activation)
    
    outlayer_activation = np.dot(hidlayer_output,output_weights)
    outlayer_activation = outlayer_activation + output_bias
    pred_output = sigmoid(outlayer_activation)

    #Backpropagation for the network
    e = target_array - pred_output
    d_pred_output = e * backward(pred_output)
    
    error_hidden_layer = np.dot(d_pred_output,output_weights.T)
    d_hidden_layer = error_hidden_layer * backward(hidlayer_output)
    
    # Updating Weights and Biases after back propogation
    output_weights = output_weights + hidlayer_output.T.dot(d_pred_output) * l_rate
    output_bias = output_bias + np.sum(d_pred_output,axis=0,keepdims=True) * l_rate
    hidden_weights = hidden_weights + input_array.T.dot(d_hidden_layer) * l_rate
    hidden_bias = hidden_bias + np.sum(d_hidden_layer,axis=0,keepdims=True) * l_rate


### looking at the final weights and biases after the training algo 

In [312]:
print("\nFinal hidden weights: (v11 v12 v21 v22)\n ",hidden_weights)
print("\nFinal hidden bias: (v01 v02) \n",hidden_bias)
print("\nFinal output weights: (w1, w2)\n ",output_weights)
print("\nFinal output bias: (w0)\n ",output_bias)


Final hidden weights: (v11 v12 v21 v22)
  [[ 0.6        -0.3       ]
 [-0.09705287  0.40061171]]

Final hidden bias: (v01 v02) 
 [[0.30294713 0.50061171]]

Final output weights: (w1, w2)
  [[0.41636688]
 [0.1211628 ]]

Final output bias: (w0)
  [[-0.17023305]]
